services:
  navimoderator_auto_clip:
    build:
      context: ../
      dockerfile: ./.devcontainer/dev.Dockerfile
    env_file:
      - ../.env
    volumes:
      - ..:/workspaces/navimoderator_auto_clip:cached
    environment:
      - PYTHONPATH=/workspaces/navimoderator_auto_clip/src