services:
  navimoderator-auto-clip:
    build:
      context: ../
      dockerfile: ./.devcontainer/dev.Dockerfile
    env_file:
      - ../.env
    volumes:
      - ..:/workspaces/navimoderator-auto-clip:cached
    environment:
      - PYTHONPATH=/workspaces/navimoderator-auto-clip/src